create-stitch-sfmc-transactions
bsd/dbt-arc-functions pull request #196
Opened 2023-03-28 21:17 UTC by dmbluestate

# Pull Request for dbt-arc-functions

- [X ] If you've created a macro, make sure it is documented by running the notebook: `process_model_documentation_codegen_output.ipynb` util in this repo

- [X ] Test branch on a development branch of an existing client (ideally the one that raised the bug). Do this by changing revision of the package to the branch name in `packages.yml` file in dbt State client below.
Client : arc-uusa

- [X ] If new macro files were created or updated, re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies

- [X ] check in dbt that client package successfully runs `dbt deps`, `dbt compile`, and `dbt run`; screenshot this page

- [X ] query the resulting staging model in bigquery (or by previewing mart in dbt cloud, or your IDE); screenshot this

- [X ] If exists, link bug issue and jira tickets to PR

2023-03-30 21:45 UTC, Frydafly requested changes
hi! just have some questions and suggestions below

2023-03-30 21:45 UTC, Frydafly commented on macros/stitch_sfmc_transactions/staging/stg_stitch_sfmc_uusa_transactions_unioned.sql
> +-- depends_on: {{ ref('stg_stitch_sfmc_fundraiseup_filtered_recent_transaction') }}
the --depends_on logic won't pass over to a client project -- can we remove it on here? it's something that the user has to add using add_dependencies, or by doing it manually

2023-03-30 21:45 UTC, Frydafly commented on macros/stitch_sfmc_transactions/staging/stg_stitch_sfmc_uusa_transactions_unioned.sql
> +{% macro create_stg_stitch_transactions_unioned() %}
question -- the macro has a different name than the model itself 

I think the macro is too general and the model name might be too specific. 

this model happens to union fundraise up and bbcrm data here, but that isn't necessarily what it's doing, it is pulling in any table that starts with src_stitch and ends with transaction. 

what if we call both the model and the macro: stg_stitch_sfmc_transactions_unioned
and remove UUSA because if we are in msf, we will build out the sources for msf and name them transaction at the end and stitch at the start, and we will still want them united at this stage?

as for the folder name, looks good and describes what we are doing!

2023-03-30 21:45 UTC, Frydafly commented on macros/stitch_sfmc_fundraiseup_transactions/staging/stg_stitch_sfmc_fundraiseup_filtered_recent_transaction.sql
> +        appeal
question on appeal! what does it mean in this case? and do you see it as a field that we will pull into other transaction tables for other clients, or is it a UUSA specific thing?

2023-03-30 21:45 UTC, Frydafly commented on macros/stitch_sfmc_fundraiseup_transactions/staging/stg_stitch_sfmc_fundraiseup_filtered_recent_transaction.sql
> +with bbcrm as(
you might be able to rename reference_name to bbcrm and then avoid having to write a CTE, and then reference {{ref(bbcrm)}}  in line 20? 

not anything important tho

2023-03-30 21:45 UTC, Frydafly commented on sources/stitch_sfmc_fundraiseup.yml
> +  - name: src_stitch_fundraiseup
can we rename the yml and the source name to be the same?

2023-03-30 21:45 UTC, Frydafly commented on sources/stitch_sfmc_bbcrm.yml
> +sources:
will it be a headache to limit this to transaction data? 

`stitch_sfmc_bbcrm_transactions` and only pull in the transaction table we need?

we've been doing that so far, not sure if it's the best practice, but we've only been writing YML for the source we pull in per mart, and making sources per mart-- I think it's also one way for the create or update standard models to pull in the source yml and write it

2023-03-30 21:52 UTC, dmbluestate commented on macros/stitch_sfmc_transactions/staging/stg_stitch_sfmc_uusa_transactions_unioned.sql
> +-- depends_on: {{ ref('stg_stitch_sfmc_fundraiseup_filtered_recent_transaction') }}
Yes! Can do. Added it in the wrong place.

2023-03-30 21:56 UTC, Frydafly commented on sources/stitch_sfmc_fundraiseup.yml
> +  - name: src_stitch_fundraiseup
naming it the above would also correspond to the source name in the macros folder

2023-03-30 21:56 UTC, Frydafly commented on sources/stitch_sfmc_bbcrm.yml
> +sources:
doing so will also name the source the same as the macros folder we need to pull in

2023-03-30 22:10 UTC, dmbluestate commented on macros/stitch_sfmc_transactions/staging/stg_stitch_sfmc_uusa_transactions_unioned.sql
> +{% macro create_stg_stitch_transactions_unioned() %}
I see your point on the model and macro names matching. and also YES on the macro name. The use-case that you describe above is exactly what I was going for but the model/macro names could use some tidying up.

2023-03-30 22:17 UTC, dmbluestate commented on macros/stitch_sfmc_fundraiseup_transactions/staging/stg_src_stitch_sfmc_fundraiseup_recent_transaction.sql
> +* Except(row_num, _sdc_received_at)
This is dedupe logic using a window function that removes duplicate transaction records because we designed time-based overlap into the sfmc automations. The overlap was a failsafe step to protect uusa's data from pipeline failures and was recommended by Christine. This type of dedupe logic was in every single model in UUSA's current repo, so I reduced it to just the src_staging models.

2023-03-30 22:21 UTC, dmbluestate commented on sources/stitch_sfmc_fundraiseup.yml
> +  - name: src_stitch_fundraiseup
I think the thing we discussed here was making sure that the yaml file and the macro directory had the same name. In the case of stitch_sfmc_email, that yml file has multiple src tables in it, but it did auto-populate when running create_or_update_standard_models because the source yaml and the macro directory names match.  I think the solution here is to match the name of the source yaml to the macro directory, but I will test and let you know :)

2023-03-30 22:27 UTC, dmbluestate commented on sources/stitch_sfmc_bbcrm.yml
> +sources:
I don't think it's a headache, but it is something that we should develop a POV on and adopt the same behavior going forward. For the stitch_sfmc_email.yml file, we pull in 10 or 12 tables into one source because they are related to email reporting. Something to keep discussing as we add sources that are just one table, or sources that have multiple tables in the BQ dataset.

2023-03-30 22:28 UTC, dmbluestate commented on sources/stitch_sfmc_bbcrm.yml
> +sources:
we also discussed an option via slack to solve this 😃

2023-03-30 23:00 UTC, dmbluestate commented on sources/stitch_sfmc_fundraiseup.yml
> +  - name: src_stitch_fundraiseup
Matching the source yaml name to the name of the macro directory worked for pulling in the sources.

2023-03-30 23:47 UTC, dmbluestate commented on macros/stitch_sfmc_fundraiseup_transactions/staging/stg_stitch_sfmc_fundraiseup_filtered_recent_transaction.sql
> +with bbcrm as(
Tested this and it created compilation errors. I think it may have something to do with the syntax and how the variables are called with jinja or the use of the ephemeral models, but the cte compiles and runs so this is something that I can research outside of this pr.

2023-03-30 23:51 UTC, dmbluestate commented
Made some of the requested changes, used add_dependencies.py to fix dependencies on the unioned model, compiled and ran successfully.

2023-04-04 17:56 UTC, Frydafly approved these changes
Great! I went into the test_stitch_sfmc_staging_tables branch of UUSA and deleted all existing models, re-ran create_or_update_standard_models on this branch (with this updated dbt-arc-functions branch), added dependencies on the unioned model, and it ran successfully!

2023-04-04 17:59 UTC, merged