Arc 1388 audience cashflow screen sfmc initiate staging tables that model donation based audience data
bsd/dbt-arc-functions pull request #201
Opened 2023-04-06 18:18 UTC by Frydafly

# Pull Request for dbt-arc-functions

- [ ] If you've created a macro, make sure it is documented by running the notebook: `process_model_documentation_codegen_output.ipynb` util in this repo

- [ ] Test branch on a development branch of an existing client (ideally the one that raised the bug). Do this by changing revision of the package to the branch name in `packages.yml` file in dbt State client below.

- [ ] If new macro files were created or updated, re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies

- [ ] check in dbt that client package successfully runs `dbt deps`, `dbt compile`, and `dbt run`; screenshot this page

- [ ] query the resulting staging model in bigquery (or by previewing mart in dbt cloud, or your IDE); screenshot this

- [ ] If exists, link bug issue and jira tickets to PR

2023-04-21 16:00 UTC, Frydafly commented
@dmbluestate @ryantimjohn -- just enrolling some help here -- no matter how many times I run sqlfmt . locally and find that all files pass formatting check, the build still fails on here. any ideas?

2023-04-21 16:13 UTC, dmbluestate commented
> @dmbluestate @ryantimjohn -- just enrolling some help here -- no matter how many times I run sqlfmt . locally and find that all files pass formatting check, the build still fails on here. any ideas?

Is this an issue with the dialect like it was for us the other day?

2023-04-21 18:28 UTC, Frydafly commented
hold on @dmbluestate -- I actually don't like what I'm seeing in the final table -- it's very repetitive.

2023-04-21 18:30 UTC, dmbluestate commented
@Frydafly, I was just getting ready to run the repo. I'll pause.

2023-04-21 18:33 UTC, Frydafly commented
and it is good to go! @dmbluestate 

<img width="1151" alt="Screenshot 2023-04-21 at 1 32 41 PM" src="https://user-images.githubusercontent.com/22733009/233710166-3f6a460b-9053-4117-8c52-bee0ebddbca3.png">

2023-04-24 21:47 UTC, dmbluestate requested changes
requesting changes for duplicated models

2023-04-25 18:19 UTC, Frydafly commented
@dmbluestate I think I can resolve this issue by truncating the transaction_date field so that it is a date, not a date time, and then aggregating results by date and person_id. working on that now.

2023-04-25 18:50 UTC, Frydafly commented
hi @dmbluestate -- the tables should no longer duplicate because they are unique to each DAY and each PERSON, so there is one line per day and person across all these tables. This is simpler anyway, given that the greatest granularity in audience change happens on a day to day basis, not on an hour to hour, etc.

2023-04-25 19:22 UTC, Frydafly commented
I'm still stuck with the silliest of issues, which is that the _append table has unnecessary duplicates. these duplicates in this case shouldn't be a problem down the line, but it's so unnecessary to have!

2023-04-25 19:50 UTC, Frydafly commented
@dmbluestate I think it's ready for re-review, but with consideration that I am still dealing with some duplicates in the final append model

2023-04-25 20:45 UTC, Frydafly commented on macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transaction_jobs.sql
these duplicates are now addressed!

2023-04-25 20:51 UTC, Frydafly commented on macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transaction_jobs_append.sql
> +                        donated_two_fiscal_years_ago_july_to_june = 1
@Frydafly TODO -- change this so that it looks at any donation made before a certain date to account for the 3rd year. rather than having to look up 3 years ago and 4 years ago.

2023-04-27 18:14 UTC, Frydafly commented on macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transaction_jobs_append.sql
> +                        donated_two_fiscal_years_ago_july_to_june = 1
done!

2023-05-01 17:51 UTC, dmbluestate commented
<img width="663" alt="Screenshot 2023-05-01 at 1 11 15 PM" src="https://user-images.githubusercontent.com/109629735/235499765-299d0219-a0be-4397-97f6-74fed929d95c.png">

Not a huge deal but in the screenshot above, the previous_latest_transaction_date has a value after the transaction date for that record. Not sure if this will mess us data downstream so just wanted to flag it here. Also, I had to push a comma to a model and that was it. Otherwise it looks good.

2023-05-01 17:54 UTC, dmbluestate approved these changes
Approved with comments.

2023-05-01 17:59 UTC, Frydafly commented
Oh! thanks for catching that, I definitely want to address that! I'm going
to copy and paste your comment and screenshot into a bug report ticket in
jira.

On Mon, May 1, 2023 at 12:52 PM Derrick Mondowney ***@***.***>
wrote:

> [image: Screenshot 2023-05-01 at 1 11 15 PM]
> <https://user-images.githubusercontent.com/109629735/235499765-299d0219-a0be-4397-97f6-74fed929d95c.png>
>
> Not a huge deal but in the screenshot above, the
> previous_latest_transaction_date has a value after the transaction date for
> that record. Not sure if this will mess us data downstream so just wanted
> to flag it here. Also, I had to push a comma to a model and that was it.
> Otherwise it looks good.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bsd/dbt-arc-functions/pull/201#issuecomment-1530008633>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFNOBUNUIRQNWDQ2GLV4NP3XD7Z4FANCNFSM6AAAAAAWVXMWCQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-01 18:01 UTC, merged

2023-05-01 18:02 UTC, Frydafly commented
@dmbluestate also any luck on your end with getting the linters to pass? I can't seem to get that working.

2023-05-01 18:45 UTC, dmbluestate commented
> @dmbluestate Also any luck on your end with getting the linters to pass? I can't get that working.
@Frydafly 
No. I saw that the yaml linter hadn't been run on the whole repo; when I ran it, I got like 214 file changes, and I didn't want to push those into the main just to pass the linter and confuse the changes since it was soo many files. It may be worth just pulling a branch to run the linter, get it to pass, and then merge. That way at least, the changes are contained to one PR that just applies linter changes.