Arc 1438 Create tool to automatically fill descriptions from OpenAI and backfill descriptions
bsd/dbt-arc-functions pull request #238
Opened 2023-06-06 19:18 UTC by ryantimjohn

2023-06-06 20:49 UTC, Frydafly requested changes
woah! ok, this fills in all our documentation, alright. 

I definitely want to merge in the documentation changes, but I think it would be helpful to make some additions to the notebook and also our readme so that: 
- a new user knows when/if/how to use the notebook (in terms of steps, you would first create macros, then run create_standard_models in your client project, then use the codegen script to create documentation yaml structure and files... and then at that point you can run the open ai script to fill in the descriptions?)
- there are some variables in the notebook, like file_path that would be nice to have up top as constants where the user can fill in the appropriate file path for new models so that the notebook fills it in 
- its assumed that the user will have an OPEN AI key in their env vars-- maybe a URL to the open AI website + a note in the notebook to `export OPEN_AI_KEY=[your key]` before running the notebook?

2023-06-07 20:46 UTC, ryantimjohn commented
@Frydafly, this all sounds reasonable! I suggest we pull out the note book from the PR so I can work on that next week and just make the docs changes.

2023-06-07 21:07 UTC, ryantimjohn commented on pull_request_template.md
> +- [ ] If you've created a macro, make sure it is documented by running the notebook: `create_docs.ipynb` util in this repo. From there, you'll have to either fill in descriptions by hand OR use our `
@Frydafly how does this look?

2023-06-07 21:08 UTC, ryantimjohn commented
@Frydafly, actually, I was able to make the changes you requested I believe. Commented on the PR template, and here's the updated notebook:
https://github.com/bsd/dbt-arc-functions/blob/022fea9289032be482e8c08af9de96e6a440fc33/utils/fill_in_descriptions_using_openai.ipynb

2023-06-07 22:11 UTC, Frydafly commented
Sounds good!

All the best,
Fryda
(she/her)
On Jun 7, 2023 at 4:08 PM -0500, Tim Ryan ***@***.***>, wrote:
> @Frydafly, actually, I was able to make the changes you requested I believe. Commented on the PR template, and here's the updated notebook:
> https://github.com/bsd/dbt-arc-functions/blob/022fea9289032be482e8c08af9de96e6a440fc33/utils/fill_in_descriptions_using_openai.ipynb
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-06-08 18:24 UTC, Frydafly approved these changes
🥳

2023-06-08 19:33 UTC, merged