ARC-1439 add audience budget
bsd/dbt-arc-functions pull request #276
Opened 2023-07-21 20:37 UTC by ryantimjohn

# Pull Request for dbt-arc-functions

- [ ] Open the pull request as a draft so that you can run tests against the code and inspect the files in the Files view of the Pull Request interface in Github.

- [ ] Once you're satisfied, convert the draft into an open Pull Request by clicking "Ready for Review" near the bottom of this page. You should not make any changes to the code except in dire emergency once you've converted from draft, so make sure you're really satisfied.

- [ ] Add two of the principal contributors to this PR for review. Currently, the principal contributors are @dmbluestate , @Frydafly , and @ryantimjohn.

- [ ] We've divided our PR templates into Macros, Utils and Docs PR requests. Delete the ones you're not using.
### Macros (delete if not using)

- [ ] Link Jira tickets (or Github Issues) to PR here. Make sure that the Jira ticket has a good description as to why this PR is necessary and the business problem that this PR is solving. Moreover, if there have been any discussions of this ticket in Slack, make sure they're linked in the Jira ticket:

- [ ] Make sure this is named using Jira extension so that naming convention is consistent. If it's not, that's okay. Go to the Jira ticket, click into the ticket, then on the right under Details, find Development, then click the Create branch button. Copy the Branch Name from there. Read here [how to rename a branch in Github](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) to rename this branch. In the future, create branches from Jira.

- [ ] Make sure the Macro is documented by running the notebook: `create_docs.ipynb` util in this repo. From there, you'll have to either fill in descriptions by hand OR use our `fill_in_descriptions_using_openai.ipynb` to fill in descriptions using OpenAI's ChatGPT. Always make sure to check over ChatGPT's column descriptions, as they're likely not perfect.

- [ ] Test branch on a development branch of an existing client (ideally the one that raised the bug). Do this by changing revision of the package to the branch name in `packages.yml` file in dbt State client below.

- [ ] If new macro files were created or updated, re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies

- [ ] check in dbt that client package successfully runs `dbt deps`, `dbt compile`, and `dbt run`; screenshot this page

- [ ] query the resulting staging model in bigquery (or by previewing mart in dbt cloud, or your IDE); screenshot this

### Utils (delete if not using)

- [ ] Link Jira tickets (or Github Issues) to PR here. Make sure that the Jira ticket has a good description as to why this PR is necessary and the business problem that this PR is solving. Moreover, if there have been any discussions of this ticket in Slack, make sure they're linked in the Jira ticket:

- [ ] Make sure this is named using Jira extension so that naming convention is consistent. If it's not, that's okay. Go to the Jira ticket, click into the ticket, then on the right under Details, find Development, then click the Create branch button. Copy the Branch Name from there. Read here [how to rename a branch in Github](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) to rename this branch. In the future, create branches from Jira.

- [ ] Suggest any tests that your PR reviewer might use to check the utils here. Better yet, if you're able, write automated tests in Github Actions!

- [ ] Update utils/README.md with any new utils. Make sure that the Table of Contents is updated (most IDEs/code editors can do this for you!)

### Docs (delete if not using)

- [ ] Link Jira tickets (or Github Issues) to PR here. Make sure that the Jira ticket has a good description as to why this PR is necessary and the business problem that this PR is solving. Moreover, if there have been any discussions of this ticket in Slack, make sure they're linked in the Jira ticket. If this is a very simple docs change, feel free to write a brief outline below instead:

## Formatters

Three different formatters will run when you open a pull request:
- [sqlfmt](http://sqlfmt.com/)
- [yamlfix](https://lyz-code.github.io/yamlfix/)
- [Black(python)](https://pypi.org/project/black/)

If any of them detect syntax problems, they will error. They will automatically open a pull request with the changes you need to make to pass the formatter. Just merge that PR and you should be good to go.

## Linters
We have two in-house linters:

### [check_for_docs_for_every_macro.py](https://github.com/bsd/dbt-arc-functions/blob/main/utils/check_for_docs_for_every_macro.py)
Just makes sure that every macro has a doc associated with it in the documentation folder with the same folder structure, i.e.:

`documentation/combined_email_paidmedia/marts/mart_combined_email_paidmedia_daily_revenue_performance.yml`

is the doc for

`       macros/combined_email_paidmedia/marts/mart_combined_email_paidmedia_daily_revenue_performance.sql`

### [check_docs_correct.py](https://github.com/bsd/dbt-arc-functions/blob/main/utils/check_docs_correct.py)
Runs through a lot of checks on documents to make sure that they are formatted to our standards. This includes checking whether docs and sources:
- have columns
- have tables
- source columns have data_type and description
- have a version number
- docs have a macro associated with them
- docs are not blank

There may be additional checks not documented here. The linter will fail on any error.

The script will document all failures and display them to you with remedies.

2023-07-21 20:46 UTC, ryantimjohn commented
@Frydafly just so you know, I'm mostly finished with this, just going to QA, will have to be next week

2023-07-25 18:54 UTC, Frydafly requested changes
some changes requested involving data types and documentation descriptions, but that's it! looking good otherwise!

2023-07-25 18:54 UTC, Frydafly commented on macros/audience_budget/staging/stg_audience_budget_by_day.sql
> +{% macro create_stg_audience_budget_by_day() %}
why not include the references (budget & datespine) as arguments?

2023-07-25 18:54 UTC, Frydafly commented on macros/audience_budget/staging/stg_audience_budget_by_day.sql
> +                extract(year from date_spine.date_day) as date_spine_year,
in the resulting query for UUSA, it looks like date_spine_year, month, and date are showing up as a floats

2023-07-25 18:54 UTC, Frydafly commented on macros/audience_budget/staging/stg_adhoc_google_spreadsheets_audience_monthly_budget.sql
> +{% macro create_stg_adhoc_google_spreadsheets_audience_monthly_budget() %}
could we potentially safe_cast values here? so that we stage the spreadsheet and make sure the correct data types are coming through downstream?

2023-07-25 18:54 UTC, Frydafly commented on documentation/audience_budget/staging/stg_adhoc_google_spreadsheets_audience_monthly_budget.yml
> +        description: Retained donors with at least 3 donations targeted for campaign
this is donors that have been retained for 3+ years

2023-07-25 18:54 UTC, Frydafly commented on documentation/audience_budget/staging/stg_adhoc_google_spreadsheets_audience_monthly_budget.yml
> +        description: Retained donor targets for campaign
these are donors that have been retained one year

2023-07-25 18:54 UTC, Frydafly commented on documentation/audience_budget/staging/stg_audience_budget_by_day.yml
> +        description: Number of retained donors with at least 3 donations targeted
"with at least 3 years as retained donors"

2023-07-27 18:40 UTC, ryantimjohn commented on macros/audience_budget/staging/stg_audience_budget_by_day.sql
> +{% macro create_stg_audience_budget_by_day() %}
Updated to use variables

2023-07-27 18:40 UTC, ryantimjohn commented on macros/audience_budget/staging/stg_audience_budget_by_day.sql
> +                extract(year from date_spine.date_day) as date_spine_year,
SAFE_CAST these as integers!

2023-07-27 18:41 UTC, ryantimjohn commented on macros/audience_budget/staging/stg_adhoc_google_spreadsheets_audience_monthly_budget.sql
> +{% macro create_stg_adhoc_google_spreadsheets_audience_monthly_budget() %}
SAFE_CAST these as the corresponding datatypes!

2023-07-27 18:56 UTC, ryantimjohn commented
Updated per @Frydafly comments, reran successfully:
![Screenshot 2023-07-27 at 2 50 12 PM](https://github.com/bsd/dbt-arc-functions/assets/16624855/85be159f-f6b0-4feb-b0d1-cf687b1165f3)

2023-07-27 19:03 UTC, ryantimjohn commented on macros/audience_budget/staging/stg_audience_budget_date_spine.sql
> +    {% endif %}
@dmbluestate I thought this was some pretty slick code for pulling the datespine between two dates. Don't know if you had a similar solution for other time where you have a datespine.

2023-07-28 13:25 UTC, merged