ARC-1503-audience-tech-planning-create-rollup-by-person-and-day-for-recurring-donors-lifetime-gift-giving-revenue-and-donor-counts-mart
bsd/dbt-arc-functions pull request #305
Opened 2023-08-24 15:58 UTC by ryantimjohn

# Pull Request for dbt-arc-functions

- [ ] Open the pull request as a draft so that you can run tests against the code and inspect the files in the Files view of the Pull Request interface in Github.

- [ ] Once you're satisfied, convert the draft into an open Pull Request by clicking "Ready for Review" near the bottom of this page. You should not make any changes to the code except in dire emergency once you've converted from draft, so make sure you're really satisfied.

- [ ] Add two of the principal contributors to this PR for review. Currently, the principal contributors are @dmbluestate , @Frydafly , and @ryantimjohn.

- [ ] We've divided our PR templates into Macros, Utils and Docs PR requests. Delete the ones you're not using.
### Macros (delete if not using)

- [ ] Link Jira tickets (or Github Issues) to PR here. Make sure that the Jira ticket has a good description as to why this PR is necessary and the business problem that this PR is solving. Moreover, if there have been any discussions of this ticket in Slack, make sure they're linked in the Jira ticket:

- [ ] Make sure this is named using Jira extension so that naming convention is consistent. If it's not, that's okay. Go to the Jira ticket, click into the ticket, then on the right under Details, find Development, then click the Create branch button. Copy the Branch Name from there. Read here [how to rename a branch in Github](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) to rename this branch. In the future, create branches from Jira.

- [ ] Make sure the Macro is documented by running the notebook: `create_docs.ipynb` util in this repo. From there, you'll have to either fill in descriptions by hand OR use our `fill_in_descriptions_using_openai.ipynb` to fill in descriptions using OpenAI's ChatGPT. Always make sure to check over ChatGPT's column descriptions, as they're likely not perfect.

- [ ] Test branch on a development branch of an existing client (ideally the one that raised the bug). Do this by changing revision of the package to the branch name in `packages.yml` file in dbt State client below.

- [ ] If new macro files were created or updated, re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies

- [ ] check in dbt that client package successfully runs `dbt deps`, `dbt compile`, and `dbt run`; screenshot this page

- [ ] query the resulting staging model in bigquery (or by previewing mart in dbt cloud, or your IDE); screenshot this

### Utils (delete if not using)

- [ ] Link Jira tickets (or Github Issues) to PR here. Make sure that the Jira ticket has a good description as to why this PR is necessary and the business problem that this PR is solving. Moreover, if there have been any discussions of this ticket in Slack, make sure they're linked in the Jira ticket:

- [ ] Make sure this is named using Jira extension so that naming convention is consistent. If it's not, that's okay. Go to the Jira ticket, click into the ticket, then on the right under Details, find Development, then click the Create branch button. Copy the Branch Name from there. Read here [how to rename a branch in Github](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) to rename this branch. In the future, create branches from Jira.

- [ ] Suggest any tests that your PR reviewer might use to check the utils here. Better yet, if you're able, write automated tests in Github Actions!

- [ ] Update utils/README.md with any new utils. Make sure that the Table of Contents is updated (most IDEs/code editors can do this for you!)

### Docs (delete if not using)

- [ ] Link Jira tickets (or Github Issues) to PR here. Make sure that the Jira ticket has a good description as to why this PR is necessary and the business problem that this PR is solving. Moreover, if there have been any discussions of this ticket in Slack, make sure they're linked in the Jira ticket. If this is a very simple docs change, feel free to write a brief outline below instead:

## Formatters

Three different formatters will run when you open a pull request:
- [sqlfmt](http://sqlfmt.com/)
- [yamlfix](https://lyz-code.github.io/yamlfix/)
- [Black(python)](https://pypi.org/project/black/)

If any of them detect syntax problems, they will error. They will automatically open a pull request with the changes you need to make to pass the formatter. Just merge that PR and you should be good to go.

## Linters
We have two in-house linters:

### [check_macros.py](https://github.com/bsd/dbt-arc-functions/blob/main/utils/check_macros.py)
Makes sure that every macro has a doc associated with it in the documentation folder with the same folder structure, i.e.:

`documentation/combined_email_paidmedia/marts/mart_combined_email_paidmedia_daily_revenue_performance.yml`

is the doc for

`       macros/combined_email_paidmedia/marts/mart_combined_email_paidmedia_daily_revenue_performance.sql`

Additionally makes sure that macros are named correctly, i.e. with the naming convention `create_(macro_file_name_stem)`

### [check_docs_correct.py](https://github.com/bsd/dbt-arc-functions/blob/main/utils/check_docs_correct.py)
Runs through a lot of checks on documents to make sure that they are formatted to our standards. This includes checking whether docs and sources:
- have columns
- have tables
- source columns have data_type and description
- have a version number
- docs have a macro associated with them
- docs are not blank
- that model names match the filename stem

There may be additional checks not documented here. The linter will fail on any error.

The script will document all failures and display them to you with remedies.

2023-08-24 18:55 UTC, Frydafly requested changes
LGTM - few minor changes

2023-08-24 18:55 UTC, Frydafly commented on macros/stitch_sfmc_arc/marts/mart_stitch_sfmc_arc_revenue_and_donor_count_by_lifetime_gifts.sql
> +        extract(year from transaction_date_day) as transaction_date_year,
hallo! can we shift transaction_date_year and transaction_date_month to integer value? it looks like it's showing up as float in the mart screenshot

2023-08-24 18:55 UTC, Frydafly commented on documentation/stitch_sfmc_arc/marts/mart_stitch_sfmc_arc_revenue_and_donor_count_by_lifetime_gifts.yml
> +  - name: mart_stitch_sfmc_arc_revenue_and_donor_count_by_lifetime_gifts
given we intend to have this model/mart for data that isn't sfmc or stitch related in the future, could we remove the reference to "stitch_sfmc" from the mart? if you have a reason though, I'm interested in learning why this might actually be better!

2023-08-24 19:08 UTC, ryantimjohn commented on macros/stitch_sfmc_arc/marts/mart_stitch_sfmc_arc_revenue_and_donor_count_by_lifetime_gifts.sql
> +        extract(year from transaction_date_day) as transaction_date_year,
These are ints, unfortunately dbt preview always displays everything as floats:
![Screenshot 2023-08-24 at 3 06 33 PM](https://github.com/bsd/dbt-arc-functions/assets/16624855/14a47180-a581-4eee-96f7-bf987935ac84)
Will start taking screenshots out of BigQuery instead going forward!

2023-08-24 19:14 UTC, ryantimjohn commented on documentation/stitch_sfmc_arc/marts/mart_stitch_sfmc_arc_revenue_and_donor_count_by_lifetime_gifts.yml
> +  - name: mart_stitch_sfmc_arc_revenue_and_donor_count_by_lifetime_gifts
So, to do, on top of current mart, we'd have to build a new mart in a separate folder that aggregated from multiple sources, which we should do at some point and I can do now! But that would require one of these `dbt_utils.union_relations(relations)` like here:
https://github.com/bsd/dbt-arc-functions/blob/main/macros/email/staging/stg_email_jobs_unioned.sql

which I'm happy to build on top of what we have!

2023-08-24 21:15 UTC, ryantimjohn commented on documentation/stitch_sfmc_arc/marts/mart_stitch_sfmc_arc_revenue_and_donor_count_by_lifetime_gifts.yml
> +  - name: mart_stitch_sfmc_arc_revenue_and_donor_count_by_lifetime_gifts
Alright, done, ready for re-review!

2023-08-24 21:51 UTC, Frydafly commented on macros/stitch_sfmc_arc/marts/mart_stitch_sfmc_arc_revenue_and_donor_count_by_lifetime_gifts.sql
> +        extract(year from transaction_date_day) as transaction_date_year,
oh oh ohhhh

2023-08-24 21:51 UTC, Frydafly commented on documentation/stitch_sfmc_arc/marts/mart_stitch_sfmc_arc_revenue_and_donor_count_by_lifetime_gifts.yml
> +  - name: mart_stitch_sfmc_arc_revenue_and_donor_count_by_lifetime_gifts
yay!

2023-08-24 21:52 UTC, Frydafly approved these changes
awesome!

2023-08-31 00:22 UTC, dmbluestate approved these changes

2023-08-31 13:28 UTC, merged