Arc 1602 audience tech planning add four columns to the cashflow mart that represent previous year s and two year s ago data
bsd/dbt-arc-functions pull request #317
Opened 2023-09-07 19:03 UTC by Frydafly

# Pull Request for dbt-arc-functions

- [x] Open the pull request as a draft so that you can run tests against the code and inspect the files in the Files view of the Pull Request interface in Github.

- [ ] Once you're satisfied, convert the draft into an open Pull Request by clicking "Ready for Review" near the bottom of this page. You should not make any changes to the code except in dire emergency once you've converted from draft, so make sure you're really satisfied.

- [ ] Add two of the principal contributors to this PR for review. Currently, the principal contributors are @dmbluestate , @Frydafly , and @ryantimjohn.

- [ ] We've divided our PR templates into Macros, Utils and Docs PR requests. Delete the ones you're not using.
### Macros (delete if not using)

- [ ] Link Jira tickets (or Github Issues) to PR here. Make sure that the Jira ticket has a good description as to why this PR is necessary and the business problem that this PR is solving. Moreover, if there have been any discussions of this ticket in Slack, make sure they're linked in the Jira ticket:

- [x] Make sure this is named using Jira extension so that naming convention is consistent. If it's not, that's okay. Go to the Jira ticket, click into the ticket, then on the right under Details, find Development, then click the Create branch button. Copy the Branch Name from there. Read here [how to rename a branch in Github](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) to rename this branch. In the future, create branches from Jira.

- [ ] Make sure the Macro is documented by running the notebook: `create_docs.ipynb` util in this repo. From there, you'll have to either fill in descriptions by hand OR use our `fill_in_descriptions_using_openai.ipynb` to fill in descriptions using OpenAI's ChatGPT. Always make sure to check over ChatGPT's column descriptions, as they're likely not perfect.

- [x] Test branch on a development branch of an existing client (ideally the one that raised the bug). Do this by changing revision of the package to the branch name in `packages.yml` file in dbt State client below.

- [NA] If new macro files were created or updated, re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies

- [x] check in dbt that client package successfully runs `dbt deps`, `dbt compile`, and `dbt run`; screenshot this page
<img width="730" alt="Screenshot 2023-09-07 at 2 01 54 PM" src="https://github.com/bsd/dbt-arc-functions/assets/22733009/4ffb9ee4-ba1a-494a-a836-e2390e3fbac8">

- [x] query the resulting staging model in bigquery (or by previewing mart in dbt cloud, or your IDE); screenshot this
<img width="1004" alt="Screenshot 2023-09-07 at 2 02 25 PM" src="https://github.com/bsd/dbt-arc-functions/assets/22733009/4434fbf3-1ce2-4373-a7ef-ecfb57142543">

## Formatters

Three different formatters will run when you open a pull request:
- [sqlfmt](http://sqlfmt.com/)
- [yamlfix](https://lyz-code.github.io/yamlfix/)
- [Black(python)](https://pypi.org/project/black/)

If any of them detect syntax problems, they will error. They will automatically open a pull request with the changes you need to make to pass the formatter. Just merge that PR and you should be good to go.

## Linters
We have two in-house linters:

### [check_macros.py](https://github.com/bsd/dbt-arc-functions/blob/main/utils/check_macros.py)
Makes sure that every macro has a doc associated with it in the documentation folder with the same folder structure, i.e.:

`documentation/combined_email_paidmedia/marts/mart_combined_email_paidmedia_daily_revenue_performance.yml`

is the doc for

`       macros/combined_email_paidmedia/marts/mart_combined_email_paidmedia_daily_revenue_performance.sql`

Additionally makes sure that macros are named correctly, i.e. with the naming convention `create_(macro_file_name_stem)`

### [check_docs_correct.py](https://github.com/bsd/dbt-arc-functions/blob/main/utils/check_docs_correct.py)
Runs through a lot of checks on documents to make sure that they are formatted to our standards. This includes checking whether docs and sources:
- have columns
- have tables
- source columns have data_type and description
- have a version number
- docs have a macro associated with them
- docs are not blank
- that model names match the filename stem

There may be additional checks not documented here. The linter will fail on any error.

The script will document all failures and display them to you with remedies.

2023-09-12 18:58 UTC, dmbluestate requested changes

2023-09-12 18:58 UTC, dmbluestate commented on macros/stitch_sfmc_audience_transaction/marts/mart_cashflow_actuals_and_budget_1x_revenue.sql
still seeing duplicates here.
<img width="1267" alt="Screenshot 2023-09-12 at 2 50 38 PM" src="https://github.com/bsd/dbt-arc-functions/assets/109629735/f38147b3-5a56-4e62-8eb4-c7ae61d7b574">

2023-09-12 20:24 UTC, Frydafly commented on macros/stitch_sfmc_audience_transaction/marts/mart_cashflow_actuals_and_budget_1x_revenue.sql
will work on that!

2023-09-12 22:27 UTC, Frydafly commented on macros/stitch_sfmc_audience_transaction/marts/mart_cashflow_actuals_and_budget_1x_revenue.sql
@dmbluestate addressed the duplicates

2023-09-12 22:29 UTC, Frydafly commented
While addressing the duplicates, also addressed the missing information in cases where previous years data does not perfectly match up to the current transaction -- now there should be cases where we have a date, an audience, a channel, all without revenue or gifts or even a budget assigned to it, and if the previous year or two years from then, there was a value for revenue, it will show up as a mostly blank row with key information and will have the previous years revenue. 

@dmbluestate

2023-09-13 19:36 UTC, Frydafly commented on macros/audience_budget/staging/stg_audience_budget_by_day_enriched.sql
> +        as fiscal_year,  -- not sure if this is needed here yet or if we can just keep date_day
remove comment

2023-09-13 19:37 UTC, Frydafly commented on macros/stitch_sfmc_arc/staging/stg_stitch_sfmc_arc_audience_union_transaction_joined_enriched.sql
> +        }} as fiscal_year,  -- not sure if this field is needed just yet here
remove comment

2023-09-13 19:37 UTC, Frydafly commented on macros/stitch_sfmc_audience_transaction/marts/mart_cashflow_actuals_and_budget.sql
> +            select
this date_day is correct for the dateoffset left join match, but the full outer join brings in the date_day one year too early or two years too early.

2023-09-13 19:38 UTC, dmbluestate requested changes

2023-09-13 19:38 UTC, dmbluestate commented on macros/stitch_sfmc_audience_transaction/marts/mart_cashflow_actuals_and_budget.sql
<img width="1708" alt="Screenshot 2023-09-13 at 3 28 34 PM" src="https://github.com/bsd/dbt-arc-functions/assets/109629735/7af5e934-1c65-4a11-94cd-c98e70914756">

Still seeing some issues with the duplicate rows. The actuals are calculating correctly, but there's something wonky with the budget numbers and the date day.

2023-09-13 20:10 UTC, Frydafly commented on macros/stitch_sfmc_audience_transaction/marts/mart_cashflow_actuals_and_budget.sql
alrighty! reiterating here from our convo that the date_day value is the biggest issue, requiring an addition of one year for cases where we are looking at the prev one year value and an addition of two for the two year value.

2023-09-13 20:51 UTC, Frydafly commented on macros/stitch_sfmc_audience_transaction/marts/mart_cashflow_actuals_and_budget.sql
@dmbluestate I made changes that I think might work, here is the equivalent query from above

```
SELECT * FROM `bsd-arc-uusa.dbt_fguedes_marts.mart_cashflow_actuals_and_budget` 
where month = 3
and day = 22
and donor_audience = 'grassroots'
and channel = 'email'
order by 5 desc
LIMIT 1000
```

would you be able to run this in bigquery and double check?

2023-09-13 21:00 UTC, Frydafly commented on macros/stitch_sfmc_audience_transaction/marts/mart_cashflow_actuals_and_budget.sql
> +            select
done!

2023-09-13 21:53 UTC, dmbluestate commented on macros/stitch_sfmc_audience_transaction/marts/mart_cashflow_actuals_and_budget.sql
> +                dateoffset.total_revenue_actuals
just a Missing comma here.

2023-09-13 22:33 UTC, dmbluestate commented on macros/stitch_sfmc_audience_transaction/marts/mart_cashflow_actuals_and_budget.sql
Tested and can confirm all the math checks out. Still a remaining issue here for the 2025 year we still have two rows, one for the budget and one for the actuals. This only happens when filtering for a month and day that is before the fiscal year change over. So I tested for 3/22.4/22. and 6/15 and got the same results. One extra row for 2025 where the budget and actuals are on different rows, although they are calculating correctly.

2023-09-13 22:33 UTC, dmbluestate approved these changes

2023-09-14 15:14 UTC, ryantimjohn approved these changes

2023-09-14 16:00 UTC, merged