[WIP] Add globalmessage email mart
bsd/dbt-arc-functions pull request #40
Opened 2022-05-26 17:10 UTC by Frydafly

work in progress PR

testing right now in dbt cloud

2022-05-26 17:15 UTC, Frydafly commented
Update: `dbt deps` and `dbt compile` runs successfully in dbt cloud

2022-05-26 22:37 UTC, cndege requested changes
Awesome work!! Saw some syntax issues, may be worthwhile to deploy this on a project and run all these models to ensure that nothing is missing.

Going to be offline til Tuesday, feel free to merge when @ryantimjohn approves. Thank you!

2022-05-26 22:37 UTC, cndege commented on macros/email/marts/mart_email_performance_with_revenue.sql
> +    transaction.message_set,
I believe these should be transaction**s** vs transaction?

2022-05-26 22:37 UTC, cndege commented on macros/frakture_everyaction_email/staging/stg_frakture_everyaction_email_bounces_rollup.sql
> -{% macro create_stg_frakture_everyaction_email_bounces_rollup(
Should we keep these files for backwards compatibility @ryantimjohn and @Frydafly in case other ARC projects want to upgrade but also still utilize the everyaction_email models?

2022-05-26 22:37 UTC, cndege commented on macros/frakture_global_message_email/staging/stg_frakture_global_message_email_jobs.sql
> +
nit: cleanup lines

2022-05-26 22:37 UTC, cndege commented on macros/frakture_global_message_email/staging/stg_frakture_global_message_email_unsubscribes_rollup.sql
> +SELECT DISTINCT SAFE_CAST(message_id AS STRING) AS message_id
missing a comma

2022-05-26 22:37 UTC, cndege commented on macros/frakture_global_message_email/staging/stg_frakture_global_message_email_recipients_rollup.sql
> +SELECT DISTINCT SAFE_CAST(message_id AS STRING) AS message_id
missing comma

2022-05-26 22:37 UTC, cndege commented on macros/frakture_global_message_email/staging/stg_frakture_global_message_email_bounces_rollup.sql
> +SELECT DISTINCT SAFE_CAST(message_id AS STRING) AS message_id
missing comma

2022-05-26 22:37 UTC, cndege commented on macros/frakture_global_message_email/staging/stg_frakture_global_message_email_bounces_rollup.sql
> +{% endmacro %}
nit: add new line at end of files

2022-05-27 15:30 UTC, Frydafly commented on macros/email/marts/mart_email_performance_with_revenue.sql
> +    transaction.message_set,
thank you YES @cndege I'll make the change right now

2022-05-27 18:39 UTC, ryantimjohn commented on macros/frakture_everyaction_email/staging/stg_frakture_everyaction_email_bounces_rollup.sql
> -{% macro create_stg_frakture_everyaction_email_bounces_rollup(
I think that's a good idea @cndege, the package is developed enough at this point that we probably shouldn't kill this. At least... maybe we should make an update where we don't kill this but add the global message, then a separate update where we just kill the everyaction stuff, which will be a major version number bump (as any breaking change should be.

2022-05-27 19:14 UTC, ryantimjohn commented
<img width="1180" alt="Screen Shot 2022-05-27 at 3 14 04 PM" src="https://user-images.githubusercontent.com/16624855/170775884-83bcf4ec-547f-425a-85d8-8c0ecbe107fa.png">
@Frydafly I made some edits but it now works!

2022-05-27 19:14 UTC, ryantimjohn commented
@jacksteadman

2022-05-27 19:14 UTC, ryantimjohn approved these changes

2022-05-27 20:22 UTC, Frydafly commented
> <img alt="Screen Shot 2022-05-27 at 3 14 04 PM" width="1180" src="https://user-images.githubusercontent.com/16624855/170775884-83bcf4ec-547f-425a-85d8-8c0ecbe107fa.png">
> @Frydafly I made some edits but it now works!

Awesome!

2022-05-27 20:22 UTC, Frydafly commented
> Awesome work!! Saw some syntax issues, may be worthwhile to deploy this on a project and run all these models to ensure that nothing is missing.
> 
> Going to be offline til Tuesday, feel free to merge when @ryantimjohn approves. Thank you!

Thank you! I made all of these changes.

2022-05-29 00:33 UTC, ryantimjohn commented
<img width="1779" alt="Screen Shot 2022-05-28 at 8 33 10 PM" src="https://user-images.githubusercontent.com/16624855/170847068-22e891b4-6060-4d5b-b8f9-715f4bc61d07.png">
Yay!

2022-05-29 00:34 UTC, merged