Add_stitch_copy
bsd/dbt-arc-functions pull request #41
Opened 2022-06-15 22:31 UTC by ryantimjohn

Add a script to copy datasets from stitch

2022-06-16 17:44 UTC, Frydafly requested changes
hi! I tried running this notebook locally and ran into a few issues. might just be things I don't know, and even so, would be good to add to the documentation so someone like me could run successfully?

2022-06-16 17:44 UTC, Frydafly commented on utils/create_views_from_stitch_datasets.ipynb
> +    "PROJECT_ID = \"[your-project-id]\" \n",
for my own reference -- what is the project ID for this? (that is in the GCP project?)

2022-06-16 17:44 UTC, Frydafly commented on utils/create_views_from_stitch_datasets.ipynb
> +    "print(search_statement)"
ran this notebook using `bsd-oxfam` and there was no search_statement printed in my notebook -- is that fine, or should there be a flag if that happens?

2022-06-16 17:44 UTC, Frydafly commented on utils/create_views_from_stitch_datasets.ipynb
> +    "                print(f\"\\nFinished {dataset_id}!\")\n",
@ryantimjohn got this error `DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started`

Did I miss somewhere I could save the credentials json? @ryantimjohn

2022-06-16 22:31 UTC, ryantimjohn commented
@Frydafly this one is meant to be run in a VertexAI notebook where those values are taken care of, will add that to a markdown cell on top and also to README!

Will also need to do some service account work to make these notebooks work. I'll add that to the Markdown file at the top, too!

2022-06-17 00:06 UTC, ryantimjohn commented
![Screen Shot 2022-06-16 at 8 05 33 PM](https://user-images.githubusercontent.com/16624855/174197359-0ed4bdf2-48ff-4359-826c-f7ce0521a5bd.png)
Fryda, added a bunch of documentation. Let me know if this works for you!

2022-06-17 00:06 UTC, ryantimjohn commented
![Screen Shot 2022-06-16 at 8 05 33 PM](https://user-images.githubusercontent.com/16624855/174197359-0ed4bdf2-48ff-4359-826c-f7ce0521a5bd.png)
@Frydafly, added a bunch of documentation. Let me know if this works for you!

2022-06-17 01:48 UTC, Frydafly commented
So perfect!! Thank you

All the best,
Fryda
(she/her)
On Jun 16, 2022, 7:06 PM -0500, Tim Ryan ***@***.***>, wrote:
>
> @Frydafly, added a bunch of documentation. Let me know if this works for you!
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-06-17 20:05 UTC, ryantimjohn commented
Also added this documentation to the clone tables script.

2022-06-17 20:12 UTC, ryantimjohn commented
And added an explainer to README.md

2022-06-17 20:14 UTC, ryantimjohn commented
I'm going to say that this is good now. @Frydafly if you want to try to run this in a VertexAI notebook, please give it a shot!

2022-06-17 20:15 UTC, merged