Arc 1758 audience reporting new donor logic in donor counts needs to be for first ever donation
bsd/dbt-arc-functions pull request #480
Opened 2024-01-18 16:18 UTC by Frydafly

# Pull Request for dbt-arc-functions

- [ ] Open the pull request as a draft so that you can run tests against the code and inspect the files in the Files view of the Pull Request interface in Github.

- [ ] Once you're satisfied, convert the draft into an open Pull Request by clicking "Ready for Review" near the bottom of this page. You should not make any changes to the code except in dire emergency once you've converted from draft, so make sure you're really satisfied.

- [ ] Add two of the principal contributors to this PR for review. Currently, the principal contributors are @dmbluestate , @Frydafly , and @ryantimjohn.

- [ ] We've divided our PR templates into Macros, Utils and Docs PR requests. Delete the ones you're not using.
### Macros (delete if not using)

- [ ] Link Jira tickets (or Github Issues) to PR here. Make sure that the Jira ticket has a good description as to why this PR is necessary and the business problem that this PR is solving. Moreover, if there have been any discussions of this ticket in Slack, make sure they're linked in the Jira ticket:

- [ ] Make sure this is named using Jira extension so that naming convention is consistent. If it's not, that's okay. Go to the Jira ticket, click into the ticket, then on the right under Details, find Development, then click the Create branch button. Copy the Branch Name from there. Read here [how to rename a branch in Github](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) to rename this branch. In the future, create branches from Jira.

- [ ] Make sure the Macro is documented by running the notebook: `create_docs.ipynb` util in this repo. From there, you'll have to either fill in descriptions by hand OR use our `fill_in_descriptions_using_openai.ipynb` to fill in descriptions using OpenAI's ChatGPT. Always make sure to check over ChatGPT's column descriptions, as they're likely not perfect.

- [ ] Test branch on a development branch of an existing client (ideally the one that raised the bug). Do this by changing revision of the package to the branch name in `packages.yml` file in dbt State client below.

- [ ] If new macro files were created or updated, re-run `create_or_update_standard_models.py` for the client dbt project, replacing models and dependencies

- [ ] check in dbt that client package successfully runs `dbt deps`, `dbt compile`, and `dbt run`; screenshot this page

- [ ] query the resulting staging model in bigquery (or by previewing mart in dbt cloud, or your IDE); screenshot this

### Utils (delete if not using)

- [ ] Link Jira tickets (or Github Issues) to PR here. Make sure that the Jira ticket has a good description as to why this PR is necessary and the business problem that this PR is solving. Moreover, if there have been any discussions of this ticket in Slack, make sure they're linked in the Jira ticket:

- [ ] Make sure this is named using Jira extension so that naming convention is consistent. If it's not, that's okay. Go to the Jira ticket, click into the ticket, then on the right under Details, find Development, then click the Create branch button. Copy the Branch Name from there. Read here [how to rename a branch in Github](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) to rename this branch. In the future, create branches from Jira.

- [ ] Suggest any tests that your PR reviewer might use to check the utils here. Better yet, if you're able, write automated tests in Github Actions!

- [ ] Update utils/README.md with any new utils. Make sure that the Table of Contents is updated (most IDEs/code editors can do this for you!)

### Docs (delete if not using)

- [ ] Link Jira tickets (or Github Issues) to PR here. Make sure that the Jira ticket has a good description as to why this PR is necessary and the business problem that this PR is solving. Moreover, if there have been any discussions of this ticket in Slack, make sure they're linked in the Jira ticket. If this is a very simple docs change, feel free to write a brief outline below instead:

## Formatters

Three different formatters will run when you open a pull request:
- [sqlfmt](http://sqlfmt.com/)
- [yamlfix](https://lyz-code.github.io/yamlfix/)
- [Black(python)](https://pypi.org/project/black/)

If any of them detect syntax problems, they will error. They will automatically open a pull request with the changes you need to make to pass the formatter. Just merge that PR and you should be good to go.

## Linters
We have two in-house linters:

### [check_macros.py](https://github.com/bsd/dbt-arc-functions/blob/main/utils/check_macros.py)
Makes sure that every macro has a doc associated with it in the documentation folder with the same folder structure, i.e.:

`documentation/combined_email_paidmedia/marts/mart_combined_email_paidmedia_daily_revenue_performance.yml`

is the doc for

`       macros/combined_email_paidmedia/marts/mart_combined_email_paidmedia_daily_revenue_performance.sql`

Additionally makes sure that macros are named correctly, i.e. with the naming convention `create_(macro_file_name_stem)`

### [check_docs_correct.py](https://github.com/bsd/dbt-arc-functions/blob/main/utils/check_docs_correct.py)
Runs through a lot of checks on documents to make sure that they are formatted to our standards. This includes checking whether docs and sources:
- have columns
- have tables
- source columns have data_type and description
- have a version number
- docs have a macro associated with them
- docs are not blank
- that model names match the filename stem

There may be additional checks not documented here. The linter will fail on any error.

The script will document all failures and display them to you with remedies.

2024-01-20 21:23 UTC, Frydafly commented
I wanted to note that this change creates added complexity in the donor counts staging models, which is causing it to fail due to a timeout in the dev tests. 

However, I can confirm that when reducing the time period to a few years in my local environment, all passed. Note: I have added a config so that only a limited historical period runs in dev, in order to avoid waiting forever when developing. 

<img width="888" alt="Screenshot 2024-01-20 at 3 20 05 PM" src="https://github.com/bsd/dbt-arc-functions/assets/22733009/a0f2f171-3c91-4a4f-9d97-0bd818f00ca5">

How I intend to deal with this in prod:

- [ ] approval of this, i will manually load in these models on a year by year basis to prod (unless anyone can think of a better / more efficient way!) and then 
- [ ] the models have been changed into incremental models now, so after the initial dump of data, it can update itself and continue to succeed in production

2024-01-20 21:25 UTC, Frydafly commented
Also, sqlfmt and yamlfix are failing, and the PRs aren't showing up anymore. 

I didn't want to manually do sqlfmt or yamlfix before review, bc I think it'll make it harder for you to see the changes @dmbluestate and @ryantimjohn , so my plan is to run the sqlfmt and yamlfix only after the PR is approved

TO DO: 
- [] run yamlfix and sqlfmt after PR is approved

2024-01-23 00:31 UTC, dmbluestate requested changes
Exploding join that is getting larger with every day of transactions may cause both accuracy and performance issues. Other comments are informational, suggestions, etc

2024-01-23 00:31 UTC, dmbluestate commented on macros/utils/util_stg_audience_frequency_donor_counts_interval_rollup.sql
When this  macro is called as written, it's joining two really large tables. Fixing the exploding join on the cross join table will help, but otherwise Im not sure I'm very clear on the person_and_transaction table, I'm not sure I understand why we need the grain of that table to be one row per person per day. Just trying to think of ways to reduce the size of the tables and reduce the resource load here.

2024-01-23 18:24 UTC, Frydafly commented on macros/audience_budget_with_audience_transaction/staging/stg_audience_transaction_onetime_donor_counts_actuals_rollup_unioned.sql
yeah i agree, id don't think we need this model because it is a duplicate, and i don't believe this was made in order to account for future plans

sounds like a good candidate for deduplication in the future

2024-01-23 18:24 UTC, Frydafly commented on macros/stitch_sfmc_arc/staging/stg_audience_channel_by_day_cross_join.sql
thank you!! i made changes to address the explosion

2024-01-23 18:44 UTC, dmbluestate commented on macros/utils/util_stg_audience_frequency_donor_counts_interval_rollup.sql
this one!

2024-01-23 18:51 UTC, Frydafly commented on macros/utils/util_stg_audience_frequency_donor_counts_interval_rollup.sql
> +        ) as unique_total{% if frequency == 'recurring' %}_recur_{% else %}_onetime_{% endif %}donor_counts,
done -- you will see this change in commits

2024-01-23 18:52 UTC, Frydafly commented on macros/audience_budget_with_audience_transaction/staging/stg_audience_transaction_onetime_donor_counts_actuals_rollup_unioned.sql
agreed -- it's duplicative

2024-01-23 18:53 UTC, Frydafly commented on macros/utils/util_stg_audience_frequency_donor_counts_interval_rollup.sql
> +        ) as unique_total{% if frequency == 'recurring' %}_recur_{% else %}_onetime_{% endif %}donor_counts,
done in commit!

2024-01-23 18:53 UTC, Frydafly commented on macros/utils/util_stg_audience_frequency_donor_counts_interval_rollup.sql
> +        ) as unique_newFY{% if frequency == 'recurring' %}_recur_{% else %}_onetime_{% endif %}donor_counts,
👍

2024-01-23 20:33 UTC, dmbluestate approved these changes
Besides some null audience values that we were expecting this looks like it the exploding join was fixed :)

2024-01-23 21:04 UTC, merged